/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "sigs.k8s.io/kwok/pkg/apis/v1alpha1"
	scheme "sigs.k8s.io/kwok/pkg/client/clientset/versioned/scheme"
)

// ClusterPortForwardsGetter has a method to return a ClusterPortForwardInterface.
// A group's client should implement this interface.
type ClusterPortForwardsGetter interface {
	ClusterPortForwards() ClusterPortForwardInterface
}

// ClusterPortForwardInterface has methods to work with ClusterPortForward resources.
type ClusterPortForwardInterface interface {
	Create(ctx context.Context, clusterPortForward *v1alpha1.ClusterPortForward, opts v1.CreateOptions) (*v1alpha1.ClusterPortForward, error)
	Update(ctx context.Context, clusterPortForward *v1alpha1.ClusterPortForward, opts v1.UpdateOptions) (*v1alpha1.ClusterPortForward, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterPortForward *v1alpha1.ClusterPortForward, opts v1.UpdateOptions) (*v1alpha1.ClusterPortForward, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterPortForward, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterPortForwardList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterPortForward, err error)
	ClusterPortForwardExpansion
}

// clusterPortForwards implements ClusterPortForwardInterface
type clusterPortForwards struct {
	*gentype.ClientWithList[*v1alpha1.ClusterPortForward, *v1alpha1.ClusterPortForwardList]
}

// newClusterPortForwards returns a ClusterPortForwards
func newClusterPortForwards(c *KwokV1alpha1Client) *clusterPortForwards {
	return &clusterPortForwards{
		gentype.NewClientWithList[*v1alpha1.ClusterPortForward, *v1alpha1.ClusterPortForwardList](
			"clusterportforwards",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.ClusterPortForward { return &v1alpha1.ClusterPortForward{} },
			func() *v1alpha1.ClusterPortForwardList { return &v1alpha1.ClusterPortForwardList{} }),
	}
}
