/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "sigs.k8s.io/kwok/pkg/apis/v1alpha1"
	scheme "sigs.k8s.io/kwok/pkg/client/clientset/versioned/scheme"
)

// ClusterAttachesGetter has a method to return a ClusterAttachInterface.
// A group's client should implement this interface.
type ClusterAttachesGetter interface {
	ClusterAttaches() ClusterAttachInterface
}

// ClusterAttachInterface has methods to work with ClusterAttach resources.
type ClusterAttachInterface interface {
	Create(ctx context.Context, clusterAttach *v1alpha1.ClusterAttach, opts v1.CreateOptions) (*v1alpha1.ClusterAttach, error)
	Update(ctx context.Context, clusterAttach *v1alpha1.ClusterAttach, opts v1.UpdateOptions) (*v1alpha1.ClusterAttach, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterAttach *v1alpha1.ClusterAttach, opts v1.UpdateOptions) (*v1alpha1.ClusterAttach, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterAttach, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterAttachList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterAttach, err error)
	ClusterAttachExpansion
}

// clusterAttaches implements ClusterAttachInterface
type clusterAttaches struct {
	*gentype.ClientWithList[*v1alpha1.ClusterAttach, *v1alpha1.ClusterAttachList]
}

// newClusterAttaches returns a ClusterAttaches
func newClusterAttaches(c *KwokV1alpha1Client) *clusterAttaches {
	return &clusterAttaches{
		gentype.NewClientWithList[*v1alpha1.ClusterAttach, *v1alpha1.ClusterAttachList](
			"clusterattaches",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.ClusterAttach { return &v1alpha1.ClusterAttach{} },
			func() *v1alpha1.ClusterAttachList { return &v1alpha1.ClusterAttachList{} }),
	}
}
