apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: node-not-ready
spec:
  resourceRef:
    apiGroup: v1
    kind: Node
  selector:
    matchExpressions:
    - key: '.metadata.labels["node-not-ready.stage.kwok.x-k8s.io"]'
      operator: 'In'
      values:
      - 'true'
    - key: '.status.phase'
      operator: 'In'
      values:
      - 'Running'
  delay:
    durationMilliseconds: 1000
    durationFrom:
      expressionFrom: '.metadata.annotations["node-not-ready.stage.kwok.x-k8s.io/delay"]'
    jitterDurationMilliseconds: 1000
    jitterDurationFrom:
      expressionFrom: '.metadata.annotations["node-not-ready.stage.kwok.x-k8s.io/jitter-delay"]'
  weight: 10000
  next:
    statusTemplate: |
      {{ $now := Now }}
      {{ $defaultReason := "nodeFailed" }}
      {{ $defaultMessage := "node failed" }}
      {{ $annotations := or .metadata.annotations dict }}
      {{ $failureType := or ( index $annotations "node-not-ready.stage.kwok.x-k8s.io/type" ) "" }}
      {{ $failureReason := or ( index $annotations "node-not-ready.stage.kwok.x-k8s.io/reason" ) $defaultReason }}
      {{ $failureMessage := or ( index $annotations "node-not-ready.stage.kwok.x-k8s.io/message" ) $defaultMessage }}
      {{ $lastTransitionTime := or .metadata.creationTimestamp $now }}
      conditions:
      {{ range NodeConditions }}
      {{ if eq .type "Ready" }}
      - lastHeartbeatTime: {{ $now | Quote }}
        lastTransitionTime: {{ $lastTransitionTime | Quote }}
        message: {{ $failureMessage | Quote }}
        reason: {{ $failureReason | Quote }}
        status: "False"
        type: {{ .type  | Quote}}
      {{ else if eq .type $failureType }}
      - lastHeartbeatTime: {{ $now | Quote }}
        lastTransitionTime: {{ $lastTransitionTime | Quote }}
        message: {{ $failureMessage | Quote }}
        reason: {{ $failureReason | Quote }}
        status: "True"
        type: {{ .type  | Quote}}
      {{ else }}
      - lastHeartbeatTime: {{ $now | Quote }}
        lastTransitionTime: {{ $lastTransitionTime | Quote }}
        message: {{ .message | Quote }}
        reason: {{ .reason | Quote }}
        status: {{ .status | Quote }}
        type: {{ .type  | Quote}}
      {{ end }}
      {{ end }}
