---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kwok.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kwok.labels" . | nindent 4 }}
data:
  kwok.yaml: |-
    {{- include "kwok.config" . | nindent 4 }}
