apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pv-delete
spec:
  resourceRef:
    apiGroup: v1
    kind: PersistentVolume
  selector:
    matchExpressions:
    - cel:
        expression: >-
          self.spec.storageClassName == 'kwok-volume'
    - cel:
        expression: >-
          !has(self.metadata.deletionTimestamp)
    - cel:
        expression: >-
          self.spec.persistentVolumeReclaimPolicy == 'Delete'
    - cel:
        expression: >-
          self.status.phase == 'Released'
  steps:
  - delete: true
