apiVersion: v1
kind: Pod
metadata:
  name: pod-within-limit
  namespace: default
spec:
  containers:
  - name: fake-container
    image: fake-image
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 400m
