/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/kwok/pkg/apis/operator/v1alpha1"
)

// FakeControllers implements ControllerInterface
type FakeControllers struct {
	Fake *FakeOperatorV1alpha1
	ns   string
}

var controllersResource = v1alpha1.SchemeGroupVersion.WithResource("controllers")

var controllersKind = v1alpha1.SchemeGroupVersion.WithKind("Controller")

// Get takes name of the controller, and returns the corresponding controller object, and an error if there is any.
func (c *FakeControllers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Controller, err error) {
	emptyResult := &v1alpha1.Controller{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(controllersResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Controller), err
}

// List takes label and field selectors, and returns the list of Controllers that match those selectors.
func (c *FakeControllers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ControllerList, err error) {
	emptyResult := &v1alpha1.ControllerList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(controllersResource, controllersKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ControllerList{ListMeta: obj.(*v1alpha1.ControllerList).ListMeta}
	for _, item := range obj.(*v1alpha1.ControllerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested controllers.
func (c *FakeControllers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(controllersResource, c.ns, opts))

}

// Create takes the representation of a controller and creates it.  Returns the server's representation of the controller, and an error, if there is any.
func (c *FakeControllers) Create(ctx context.Context, controller *v1alpha1.Controller, opts v1.CreateOptions) (result *v1alpha1.Controller, err error) {
	emptyResult := &v1alpha1.Controller{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(controllersResource, c.ns, controller, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Controller), err
}

// Update takes the representation of a controller and updates it. Returns the server's representation of the controller, and an error, if there is any.
func (c *FakeControllers) Update(ctx context.Context, controller *v1alpha1.Controller, opts v1.UpdateOptions) (result *v1alpha1.Controller, err error) {
	emptyResult := &v1alpha1.Controller{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(controllersResource, c.ns, controller, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Controller), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeControllers) UpdateStatus(ctx context.Context, controller *v1alpha1.Controller, opts v1.UpdateOptions) (result *v1alpha1.Controller, err error) {
	emptyResult := &v1alpha1.Controller{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(controllersResource, "status", c.ns, controller, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Controller), err
}

// Delete takes name of the controller and deletes it. Returns an error if one occurs.
func (c *FakeControllers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(controllersResource, c.ns, name, opts), &v1alpha1.Controller{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeControllers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(controllersResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ControllerList{})
	return err
}

// Patch applies the patch and returns the patched controller.
func (c *FakeControllers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Controller, err error) {
	emptyResult := &v1alpha1.Controller{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(controllersResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Controller), err
}
