apiVersion: audit.k8s.io/v1
kind: Policy
omitManagedFields: True
omitStages:
- RequestReceived
- ResponseStarted
rules:
- level: RequestResponse
  resources:
  - group: ""
    resources:
    - pods
    - pods/status
    - events
  verbs:
  - create
  - patch
  - update
  - delete
