apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  terminationGracePeriodSeconds: 30
  containers:
  - image: docker.io/library/nginx:latest
    imagePullPolicy: Always
    name: nginx
    lifecycle:
      postStart:
        exec:
          command: 
          - sleep
          - '10'
      preStop:
        exec:
          command: 
          - sleep
          - '10'
