apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kwok-dra
rules:
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceslices
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - patch
