apiVersion: config.kwok.x-k8s.io/v1alpha1
kind: KwokctlResource
metadata:
  name: node
parameters:
  allocatable:
    cpu: 32
    memory: 256Gi
    pods: 110
  capacity: {}
  nodeInfo:
    architecture: amd64
    operatingSystem: linux
  podCIDRs:
  - 10.0.0.0/24
  - fd00::/64
  nodeIPs:
  - 192.0.2.1
  - 2001:db8::1
template: |-
  kind: Node
  apiVersion: v1
  metadata:
    name: {{ Name }}
    annotations:
      kwok.x-k8s.io/node: fake
      node.alpha.kubernetes.io/ttl: "0"
      metrics.k8s.io/resource-metrics-path: "/metrics/nodes/{{ Name }}/metrics/resource"
    labels:
      beta.kubernetes.io/arch: {{ .nodeInfo.architecture }}
      beta.kubernetes.io/os: {{ .nodeInfo.operatingSystem }}
      kubernetes.io/arch: {{ .nodeInfo.architecture }}
      kubernetes.io/hostname: {{ Name }}
      kubernetes.io/os: {{ .nodeInfo.operatingSystem }}
      kubernetes.io/role: agent
      node-role.kubernetes.io/agent: ""
      type: kwok
  spec:
    {{ $index := Index }}
    {{ $podCIDRs := .podCIDRs }}
    podCIDR: {{ AddCIDR (index $podCIDRs 0) $index }}
    podCIDRs:
    {{ range $podCIDRs }}
    - {{ AddCIDR . $index }}
    {{ end }}
  status:
    addresses:
    {{ range .nodeIPs }}
    - address: {{ AddIP . $index | Quote }}
      type: InternalIP
    {{ end }}
    allocatable:
    {{ range $key, $value := .allocatable }}
      {{ $key }}: {{ $value }}
    {{ end }}
    {{ $capacity := .capacity }}
    capacity:
    {{ range $key, $value := .allocatable }}
      {{ $key }}: {{ or ( index $capacity $key ) $value }}
    {{ end }}
    nodeInfo:
    {{ range $key, $value := .nodeInfo }}
      {{ $key }}: {{ $value }}
    {{ end }}
