apiVersion: config.kwok.x-k8s.io/v1alpha1
kind: KwokctlResource
metadata:
  name: pod
parameters:
  initContainers: []
  containers:
  - name: container-0
    image: busybox
  hostNetwork: false
  nodeName: ""
template: |-
  kind: Pod
  apiVersion: v1
  metadata:
    name: {{ Name }}
    namespace: {{ or Namespace "default" }}
  spec:
    containers:
    {{ range $index, $container := .containers }}
    - name: {{ $container.name }}
      image: {{ $container.image }}
      {{ if and $container $container.resources }}
      {{ $resources := $container.resources }}
      resources:
        requests:
        {{ range $key, $value := $resources.requests }}
          {{ $key }}: {{ $value }}
        {{ end }}
        limits:
        {{ if $resources.limits  }}
        {{ range $key, $value := $resources.requests }}
          {{ $key }}: {{ or ( index $resources.limits  $key ) $value }}
        {{ end }}
        {{ else }}
        {{ range $key, $value := $resources.requests }}
          {{ $key }}: {{ $value }}
        {{ end }}
        {{ end }}
      {{ end }}
    {{ end }}
    initContainers:
    {{ range $index, $container := .initContainers }}
    - name: {{ $container.name }}
      image: {{ $container.image }}
      {{ if and $container $container.resources }}
      {{ $resources := $container.resources }}
      resources:
        requests:
        {{ range $key, $value := $resources.requests }}
          {{ $key }}: {{ $value }}
        {{ end }}
        limits:
        {{ if $resources.limits  }}
        {{ range $key, $value := $resources.requests }}
          {{ $key }}: {{ or ( index $resources.limits  $key ) $value }}
        {{ end }}
        {{ else }}
        {{ range $key, $value := $resources.requests }}
          {{ $key }}: {{ $value }}
        {{ end }}
        {{ end }}
      {{ end }}
    {{ end }}
    hostNetwork: {{ .hostNetwork }}
    nodeName: {{ .nodeName }}
