apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-create
spec:
  delay:
    durationFrom:
      jq:
        expression: .metadata.annotations["pod-create.stage.kwok.x-k8s.io/delay"]
    durationMilliseconds: 1000
    jitterDurationFrom:
      jq:
        expression: .metadata.annotations["pod-create.stage.kwok.x-k8s.io/jitter-delay"]
    jitterDurationMilliseconds: 5000
  immediateNextStage: false
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - jq:
        key: .metadata.deletionTimestamp
        operator: DoesNotExist
    - jq:
        key: .status.podIP
        operator: DoesNotExist
  steps:
  - event:
      message: Created container
      reason: Created
      type: Normal
  - patch:
      root: status
      subresource: status
      template: |
        {{ $now := Now }}

        conditions:
        {{ if .spec.initContainers }}
        - lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
          message: 'containers with incomplete status: [{{ range .spec.initContainers }} {{ .name }} {{ end }}]'
          reason: ContainersNotInitialized
          status: "False"
          type: Initialized
        {{ else }}
        - lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
          status: "True"
          type: Initialized
        {{ end }}
        - lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
          message: 'containers with unready status: [{{ range .spec.containers }} {{ .name }} {{ end }}]'
          reason: ContainersNotReady
          status: "False"
          type: Ready
        - lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
          message: 'containers with unready status: [{{ range .spec.containers }} {{ .name }} {{ end }}]'
          reason: ContainersNotReady
          status: "False"
          type: ContainersReady
        {{ range .spec.readinessGates }}
        - lastTransitionTime: {{ $now | Quote }}
          status: "True"
          type: {{ .conditionType | Quote }}
        {{ end }}

        {{ if .spec.initContainers }}
        initContainerStatuses:
        {{ range .spec.initContainers }}
        - image: {{ .image | Quote }}
          name: {{ .name | Quote }}
          ready: false
          restartCount: 0
          started: false
          state:
            waiting:
              reason: PodInitializing
        {{ end }}
        containerStatuses:
        {{ range .spec.containers }}
        - image: {{ .image | Quote }}
          name: {{ .name | Quote }}
          ready: false
          restartCount: 0
          started: false
          state:
            waiting:
              reason: PodInitializing
        {{ end }}
        {{ else }}
        containerStatuses:
        {{ range .spec.containers }}
        - image: {{ .image | Quote }}
          name: {{ .name | Quote }}
          ready: false
          restartCount: 0
          started: false
          state:
            waiting:
              reason: ContainerCreating
        {{ end }}
        {{ end }}

        hostIP: {{ NodeIPWith .spec.nodeName | Quote }}
        podIP: {{ PodIPWith .spec.nodeName ( or .spec.hostNetwork false ) ( or .metadata.uid "" ) ( or .metadata.name "" ) ( or .metadata.namespace "" ) | Quote }}
        phase: Pending
  weight: 1
  weightFrom:
    jq:
      expression: .metadata.annotations["pod-create.stage.kwok.x-k8s.io/weight"]
