apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-init-container-completed
spec:
  delay:
    durationFrom:
      jq:
        expression: .metadata.annotations["pod-init-container-completed.stage.kwok.x-k8s.io/delay"]
    durationMilliseconds: 1000
    jitterDurationFrom:
      jq:
        expression: .metadata.annotations["pod-init-container-completed.stage.kwok.x-k8s.io/jitter-delay"]
    jitterDurationMilliseconds: 5000
  immediateNextStage: false
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - jq:
        key: .metadata.deletionTimestamp
        operator: DoesNotExist
    - jq:
        key: .status.phase
        operator: In
        values:
        - Pending
    - jq:
        key: .status.initContainerStatuses.[].state.running.startedAt
        operator: Exists
  steps:
  - patch:
      root: status
      subresource: status
      template: |
        {{ $now := Now }}
        {{ $root := . }}
        conditions:
        - lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
          status: "True"
          reason: ""
          type: Initialized
        initContainerStatuses:
        {{ range $index, $item := .spec.initContainers }}
        {{ $origin := index $root.status.initContainerStatuses $index }}
        - image: {{ $item.image | Quote }}
          name: {{ $item.name | Quote }}
          ready: true
          restartCount: 0
          started: false
          state:
            terminated:
              exitCode: 0
              finishedAt: {{ $now | Quote }}
              reason: Completed
              startedAt: {{ $now | Quote }}
        {{ end }}
        containerStatuses:
        {{ range .spec.containers }}
        - image: {{ .image | Quote }}
          name: {{ .name | Quote }}
          ready: false
          restartCount: 0
          started: false
          state:
            waiting:
              reason: ContainerCreating
        {{ end }}
  weight: 1
  weightFrom:
    jq:
      expression: .metadata.annotations["pod-init-container-completed.stage.kwok.x-k8s.io/weight"]
