apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-init-container-running
spec:
  delay:
    durationFrom:
      jq:
        expression: .metadata.annotations["pod-init-container-running.stage.kwok.x-k8s.io/delay"]
    durationMilliseconds: 1000
    jitterDurationFrom:
      jq:
        expression: .metadata.annotations["pod-init-container-running.stage.kwok.x-k8s.io/jitter-delay"]
    jitterDurationMilliseconds: 5000
  immediateNextStage: false
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - jq:
        key: .metadata.deletionTimestamp
        operator: DoesNotExist
    - jq:
        key: .status.phase
        operator: In
        values:
        - Pending
    - jq:
        key: .status.conditions.[] | select( .type == "Initialized" ) | .status
        operator: NotIn
        values:
        - "True"
    - jq:
        key: .status.initContainerStatuses.[].state.waiting.reason
        operator: Exists
  steps:
  - patch:
      root: status
      subresource: status
      template: |
        {{ $now := Now }}
        {{ $root := . }}
        initContainerStatuses:
        {{ range $index, $item := .spec.initContainers }}
        {{ $origin := index $root.status.initContainerStatuses $index }}
        - image: {{ $item.image | Quote }}
          name: {{ $item.name | Quote }}
          ready: true
          restartCount: 0
          started: true
          state:
            running:
              startedAt: {{ $now | Quote }}
        {{ end }}
  weight: 1
  weightFrom:
    jq:
      expression: .metadata.annotations["pod-init-container-running.stage.kwok.x-k8s.io/weight"]
