apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-init-container-running
spec:
  delay:
    durationFrom:
      jq:
        expression: .metadata.annotations["pod-init-container-running.stage.kwok.x-k8s.io/delay"]
    durationMilliseconds: 1000
    jitterDurationFrom:
      jq:
        expression: .metadata.annotations["pod-init-container-running.stage.kwok.x-k8s.io/jitter-delay"]
    jitterDurationMilliseconds: 5000
  immediateNextStage: false
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - jq:
        key: .metadata.deletionTimestamp
        operator: DoesNotExist
    - jq:
        key: .status.conditions.[] | select( .type == "Initialized" ) | .status
        operator: NotIn
        values:
        - "True"
    - jq:
        key: .status.initContainerStatuses.[].state.waiting.reason
        operator: Exists
  steps:
  - event:
      message: 'Created container: {{ ( index .spec.containers 0 ).name }}'
      reason: Created
      type: Normal
  - patch:
      root: status
      subresource: status
      type: strategic
      template: |
        {{ define "containerStarting" }}
        {{ with .container }}
          containerID: kwok://container/{{ .name }}
          image: {{ .image | Quote }}
          imageID: kwok://image/{{ .image }}
          lastState: {}
          name: {{ .name | Quote }}
          ready: false
          {{ with .resources }}
          resources:
          {{ YAML . 1 }}
          {{ end }}
          restartCount: 0
          started: true
          state:
            running:
              startedAt: {{ Now | Quote }}
          {{ with .volumeMounts }}
          volumeMounts:
          {{ YAML . 1 }}
          {{ end }}
        {{ end }}
        {{ end }}

        initContainerStatuses:
        {{ range .spec.initContainers }}
        {{ if eq .restartPolicy "Always" }}
        -
        {{ YAML . 1 }}
        {{ else }}
        -
        {{ template "containerStarting" dict "container" . "root" $ }}
        {{ end }}
        {{ end }}
  weight: 1
  weightFrom:
    jq:
      expression: .metadata.annotations["pod-init-container-running.stage.kwok.x-k8s.io/weight"]
