apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-ready
spec:
  delay:
    durationFrom:
      jq:
        expression: .metadata.annotations["pod-ready.stage.kwok.x-k8s.io/delay"]
    durationMilliseconds: 1000
    jitterDurationFrom:
      jq:
        expression: .metadata.annotations["pod-ready.stage.kwok.x-k8s.io/jitter-delay"]
    jitterDurationMilliseconds: 5000
  immediateNextStage: false
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - jq:
        key: .metadata.deletionTimestamp
        operator: DoesNotExist
    - jq:
        key: .status.conditions.[] | select( .type == "Initialized" ) | .status
        operator: In
        values:
        - "True"
    - jq:
        key: .status.containerStatuses.[].state.waiting.reason
        operator: Exists
  steps:
  - event:
      message: 'Started container: {{ ( index .spec.containers 0 ).name }}'
      reason: Started
      type: Normal
  - patch:
      root: status
      subresource: status
      type: strategic
      template: |
        {{ $observedGeneration := or .status.observedGeneration 0 }}
        {{ define "containerStarting" }}
        {{ with .container }}
          containerID: kwok://container/{{ .name }}
          image: {{ .image | Quote }}
          imageID: kwok://image/{{ .image }}
          lastState: {}
          name: {{ .name | Quote }}
          ready: true
          {{ with .resources }}
          resources:
          {{ YAML . 1 }}
          {{ end }}
          restartCount: 0
          started: true
          state:
            running:
              startedAt: {{ Now | Quote }}
          {{ with .volumeMounts }}
          volumeMounts:
          {{ YAML . 1 }}
          {{ end }}
        {{ end }}
        {{ end }}

        $setElementOrder/conditions:
        - type: PodReadyToStartContainers
        - type: Initialized
        - type: Ready
        - type: ContainersReady
        - type: PodScheduled

        conditions:
        - lastTransitionTime: {{ Now | Quote }}
          message: null
          reason: null
          observedGeneration: {{ $observedGeneration }}
          status: "True"
          type: Ready
        - lastTransitionTime: {{ Now | Quote }}
          message: null
          reason: null
          observedGeneration: {{ $observedGeneration }}
          status: "True"
          type: ContainersReady

        containerStatuses:
        {{ range $index, $item := .spec.containers }}
        -
        {{ template "containerStarting" dict "container" . }}
        {{ end }}

        phase: Running
  weight: 1
  weightFrom:
    jq:
      expression: .metadata.annotations["pod-ready.stage.kwok.x-k8s.io/weight"]
