apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-create
spec:
  delay:
    durationFrom:
      jq:
        expression: .metadata.annotations["pod-create.stage.kwok.x-k8s.io/delay"]
    durationMilliseconds: 1000
    jitterDurationFrom:
      jq:
        expression: .metadata.annotations["pod-create.stage.kwok.x-k8s.io/jitter-delay"]
    jitterDurationMilliseconds: 5000
  immediateNextStage: false
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - jq:
        key: .metadata.deletionTimestamp
        operator: DoesNotExist
    - jq:
        key: .status.startTime
        operator: DoesNotExist
    - jq:
        key: .status.containerStatuses
        operator: DoesNotExist
  steps:
  - event:
      message: 'Created container'
      reason: Created
      type: Normal
  - patch:
      root: status
      subresource: status
      type: strategic
      template: |
        {{ $observedGeneration := add1 ( or .status.observedGeneration 0 ) }}
        {{ $hasPodScheduled := 0 }}
        {{ range .status.conditions }}
          {{ if eq .Type "PodScheduled" }}
            {{ $hasPodScheduled = 1 }}
            {{ break }}
          {{ end }}
        {{ end }}
        {{ $nodeIP := NodeIPWith .spec.nodeName | Quote }}
        {{ $podIP := PodIPWith .spec.nodeName ( or .spec.hostNetwork false ) ( or .metadata.uid "" ) ( or .metadata.name "" ) ( or .metadata.namespace "" ) | Quote }}

        {{ define "containerCreating" }}
        {{ $root := .root }}
        {{ with .container }}
          image: {{ .image | Quote }}
          imageID: kwok://image/{{ .image }}
          lastState: {}
          name: {{ .name | Quote }}
          ready: false
          {{ with .resources }}
          resources:
          {{ YAML . 1 }}
          {{ with .requests }}
          allocatedResources:
          {{ YAML . 1 }}
          {{ end }}
          {{ end }}
          restartCount: 0
          started: false
          state:
            waiting:
          {{ if $root.spec.initContainers }}
              reason: PodInitializing
          {{ else }}
              reason: ContainerCreating
          {{ end }}
          {{ with .volumeMounts }}
          volumeMounts:
          {{ YAML . 1 }}
          {{ end }}
        {{ end }}
        {{ end }}

        $setElementOrder/conditions:
        - type: PodReadyToStartContainers
        - type: Initialized
        - type: Ready
        - type: ContainersReady
        - type: PodScheduled

        conditions:
        - lastProbeTime: null
          lastTransitionTime: {{ Now | Quote }}
          observedGeneration: {{ $observedGeneration }}
          status: "True"
          type: PodReadyToStartContainers
        {{ if .spec.initContainers }}
        - lastProbeTime: null
          lastTransitionTime: {{ Now | Quote }}
          message: 'containers with incomplete status: [{{ range .spec.initContainers }} {{ .name }} {{ end }}]'
          observedGeneration: {{ $observedGeneration }}
          reason: ContainersNotInitialized
          status: "False"
          type: Initialized
        {{ else }}
        - lastProbeTime: null
          lastTransitionTime: {{ Now | Quote }}
          observedGeneration: {{ $observedGeneration }}
          status: "True"
          type: Initialized
        {{ end }}
        - lastProbeTime: null
          lastTransitionTime: {{ Now | Quote }}
          message: 'containers with unready status: [{{ range .spec.containers }} {{ .name }} {{ end }}]'
          observedGeneration: {{ $observedGeneration }}
          reason: ContainersNotReady
          status: "False"
          type: Ready
        - lastProbeTime: null
          lastTransitionTime: {{ Now | Quote }}
          message: 'containers with unready status: [{{ range .spec.containers }} {{ .name }} {{ end }}]'
          observedGeneration: {{ $observedGeneration }}
          reason: ContainersNotReady
          status: "False"
          type: ContainersReady
        {{ if $hasPodScheduled }}
        - observedGeneration: {{ $observedGeneration }}
          type: PodScheduled
        {{ else }}
        - lastProbeTime: null
          lastTransitionTime: {{ Now | Quote }}
          observedGeneration: {{ $observedGeneration }}
          status: "True"
          type: PodScheduled
        {{ end }}

        {{ with .spec.initContainers }}
        initContainerStatuses:
        {{ range . }}
        -
        {{ template "containerCreating" dict "container" . "root" $ }}
        {{ end }}
        {{ end }}

        containerStatuses:
        {{ range .spec.containers }}
        -
        {{ template "containerCreating" dict "container" . "root" $ }}
        {{ end }}

        hostIP: {{ $nodeIP }}
        podIP: {{ $podIP }}

        observedGeneration: {{ $observedGeneration }}
        startTime: {{ Now | Quote }}
  weight: 1
  weightFrom:
    jq:
      expression: .metadata.annotations["pod-create.stage.kwok.x-k8s.io/weight"]
