apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-complete
spec:
  delay:
    durationFrom:
      jq:
        expression: .metadata.annotations["pod-complete.stage.kwok.x-k8s.io/delay"]
    durationMilliseconds: 1000
    jitterDurationFrom:
      jq:
        expression: .metadata.annotations["pod-complete.stage.kwok.x-k8s.io/jitter-delay"]
    jitterDurationMilliseconds: 5000
  immediateNextStage: false
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - jq:
        key: .metadata.deletionTimestamp
        operator: DoesNotExist
    - jq:
        key: .status.phase
        operator: In
        values:
        - Running
    - jq:
        key: .status.conditions.[] | select( .type == "Ready" ) | .status
        operator: In
        values:
        - "True"
    - jq:
        key: .spec.restartPolicy
        operator: NotIn
        values:
        - Always
    - jq:
        key: .metadata.ownerReferences.[].kind
        operator: In
        values:
        - Job
  steps:
  - patch:
      root: status
      subresource: status
      type: strategic
      template: |
        {{ define "containerEnding" }}
        {{ $status := .status }}
        {{ with .container }}
          containerID: kwok://container/{{ .name }}
          image: {{ .image | Quote }}
          imageID: kwok://image/{{ .image }}
          lastState: {}
          name: {{ .name | Quote }}
          ready: true
          resources: {}
          restartCount: 0
          started: false
          state:
            terminated:
              containerID: kwok://container/{{ .name }}
              exitCode: 0
              finishedAt: {{ Now | Quote }}
              reason: Completed
              startedAt: {{ or $status.state.running.startedAt $status.state.terminated.startedAt }}
        {{ end }}
        {{ end }}

        {{ with .spec.initContainers }}
        initContainerStatuses:
        {{ range $index, $item := . }}
        {{ $status := index $.status.initContainerStatuses $index }}
        {{ if eq $item.restartPolicy "Always" }}
        -
        {{ template "containerEnding" dict "container" $item "status" $status }}
        {{ else }}
        -
        {{ YAML $status 1 }}
        {{ end }}
        {{ end }}
        {{ end }}

        containerStatuses:
        {{ range $index, $item := .spec.containers }}
        {{ $status := index $.status.containerStatuses $index }}
        -
        {{ template "containerEnding" dict "container" $item "status" $status }}
        {{ end }}

        phase: Succeeded
  weight: 1
  weightFrom:
    jq:
      expression: .metadata.annotations["pod-complete.stage.kwok.x-k8s.io/weight"]
