apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-complete
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: '.metadata.deletionTimestamp'
      operator: 'DoesNotExist'
    - key: '.status.phase'
      operator: 'In'
      values:
      - 'Running'
    - key: '.status.conditions.[] | select( .type == "Ready" ) | .status'
      operator: 'In'
      values:
      - 'True'
    - key: '.metadata.ownerReferences.[].kind'
      operator: 'In'
      values:
      - 'Job'
    - key: '.spec.restartPolicy'
      operator: 'In'
      values:
      - 'Never'
      - 'OnFailure'
  weight: 1
  weightFrom:
    expressionFrom: '.metadata.annotations["pod-complete.stage.kwok.x-k8s.io/weight"]'
  delay:
    durationMilliseconds: 1000
    durationFrom:
      expressionFrom: '.metadata.annotations["pod-complete.stage.kwok.x-k8s.io/delay"]'
    jitterDurationMilliseconds: 5000
    jitterDurationFrom:
      expressionFrom: '.metadata.annotations["pod-complete.stage.kwok.x-k8s.io/jitter-delay"]'
  next:
    delete: false
    statusTemplate: |
      {{ $now := Now }}
      {{ $root := . }}

      conditions:
      - lastTransitionTime: {{ $now | Quote }}
        reason: PodCompleted
        status: "True"
        type: Initialized
      - lastTransitionTime: {{ $now | Quote }}
        reason: PodCompleted
        status: "False"
        type: Ready
      - lastTransitionTime: {{ $now | Quote }}
        reason: PodCompleted
        status: "False"
        type: ContainersReady

      initContainerStatuses:
      {{ range $index, $item := .spec.initContainers }}
      {{ $origin := index $root.status.initContainerStatuses $index }}
      - image: {{ $item.image | Quote }}
        name: {{ $item.name | Quote }}
        restartCount: {{ $origin.restartCount }}
        started: false
        {{ if eq $item.restartPolicy "Always" }}
        ready: false
        state:
          terminated:
            exitCode: 0
            finishedAt: {{ $now | Quote }}
            reason: Completed
            startedAt: {{ ( or $origin.state.terminated.startedAt $origin.state.running.startedAt $now ) | Quote }}
        {{ else }}
        ready: {{ $origin.ready }}
        state:
          terminated:
            exitCode: 0
            finishedAt: {{ ( or $origin.state.terminated.finishedAt $now ) | Quote }}
            reason: Completed
            startedAt: {{ ( or $origin.state.terminated.startedAt $origin.state.running.startedAt $now ) | Quote }}
        {{ end }}
      {{ end }}

      containerStatuses:
      {{ range $index, $item := .spec.containers }}
      {{ $origin := index $root.status.containerStatuses $index }}
      - image: {{ $item.image | Quote }}
        name: {{ $item.name | Quote }}
        ready: {{ $origin.ready }}
        restartCount: {{ $origin.restartCount }}
        started: false
        state:
          terminated:
            exitCode: 0
            finishedAt: {{ $now | Quote }}
            reason: Completed
            startedAt: {{ ( or $origin.state.terminated.startedAt $origin.state.running.startedAt $now ) | Quote }}
      {{ end }}
      phase: Succeeded
