apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-delete
spec:
  delay:
    durationFrom:
      jq:
        expression: .metadata.annotations["pod-delete.stage.kwok.x-k8s.io/delay"]
    durationMilliseconds: 1000
    jitterDurationFrom:
      jq:
        expression: .metadata.deletionTimestamp
  immediateNextStage: false
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - jq:
        key: .metadata.deletionTimestamp
        operator: Exists
    - jq:
        key: .metadata.finalizers
        operator: DoesNotExist
  steps:
  - delete: true
  weight: 1
  weightFrom:
    jq:
      expression: .metadata.annotations["pod-delete.stage.kwok.x-k8s.io/weight"]
