apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-remove-finalizer
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: '.metadata.deletionTimestamp'
      operator: 'Exists'
    - key: '.metadata.finalizers.[]'
      operator: 'In'
      values:
      - 'kwok.x-k8s.io/fake'
  weight: 1
  weightFrom:
    expressionFrom: '.metadata.annotations["pod-remove-finalizer.stage.kwok.x-k8s.io/weight"]'
  delay:
    durationMilliseconds: 1000
    durationFrom:
      expressionFrom: '.metadata.annotations["pod-remove-finalizer.stage.kwok.x-k8s.io/delay"]'
    jitterDurationMilliseconds: 5000
    jitterDurationFrom:
      expressionFrom: '.metadata.annotations["pod-remove-finalizer.stage.kwok.x-k8s.io/jitter-delay"]'
  next:
    finalizers:
      remove:
      - value: 'kwok.x-k8s.io/fake'
    event:
      type: Normal
      reason: Killing
      message: Stopping container
