# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: kwok-operator
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: kwok-operator-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: kwok-operator
    app.kubernetes.io/part-of: kwok-operator
    app.kubernetes.io/managed-by: kustomize
  name: kwok-operator-metrics-monitor
  namespace: kwok-operator
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: kwok-operator
