//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package internalversion

import (
	unsafe "unsafe"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1alpha1 "sigs.k8s.io/kwok/pkg/apis/v1alpha1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterPortForward)(nil), (*v1alpha1.ClusterPortForward)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_ClusterPortForward_To_v1alpha1_ClusterPortForward(a.(*ClusterPortForward), b.(*v1alpha1.ClusterPortForward), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPortForwardSpec)(nil), (*v1alpha1.ClusterPortForwardSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_ClusterPortForwardSpec_To_v1alpha1_ClusterPortForwardSpec(a.(*ClusterPortForwardSpec), b.(*v1alpha1.ClusterPortForwardSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ClusterPortForwardSpec)(nil), (*ClusterPortForwardSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPortForwardSpec_To_internalversion_ClusterPortForwardSpec(a.(*v1alpha1.ClusterPortForwardSpec), b.(*ClusterPortForwardSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Component)(nil), (*v1alpha1.Component)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_Component_To_v1alpha1_Component(a.(*Component), b.(*v1alpha1.Component), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Component)(nil), (*Component)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Component_To_internalversion_Component(a.(*v1alpha1.Component), b.(*Component), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Env)(nil), (*v1alpha1.Env)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_Env_To_v1alpha1_Env(a.(*Env), b.(*v1alpha1.Env), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Env)(nil), (*Env)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Env_To_internalversion_Env(a.(*v1alpha1.Env), b.(*Env), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExpressionFromSource)(nil), (*v1alpha1.ExpressionFromSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_ExpressionFromSource_To_v1alpha1_ExpressionFromSource(a.(*ExpressionFromSource), b.(*v1alpha1.ExpressionFromSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ExpressionFromSource)(nil), (*ExpressionFromSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExpressionFromSource_To_internalversion_ExpressionFromSource(a.(*v1alpha1.ExpressionFromSource), b.(*ExpressionFromSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FinalizerItem)(nil), (*v1alpha1.FinalizerItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_FinalizerItem_To_v1alpha1_FinalizerItem(a.(*FinalizerItem), b.(*v1alpha1.FinalizerItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.FinalizerItem)(nil), (*FinalizerItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FinalizerItem_To_internalversion_FinalizerItem(a.(*v1alpha1.FinalizerItem), b.(*FinalizerItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Forward)(nil), (*v1alpha1.Forward)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_Forward_To_v1alpha1_Forward(a.(*Forward), b.(*v1alpha1.Forward), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Forward)(nil), (*Forward)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Forward_To_internalversion_Forward(a.(*v1alpha1.Forward), b.(*Forward), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ForwardTarget)(nil), (*v1alpha1.ForwardTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_ForwardTarget_To_v1alpha1_ForwardTarget(a.(*ForwardTarget), b.(*v1alpha1.ForwardTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ForwardTarget)(nil), (*ForwardTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ForwardTarget_To_internalversion_ForwardTarget(a.(*v1alpha1.ForwardTarget), b.(*ForwardTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KwokConfiguration)(nil), (*v1alpha1.KwokConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_KwokConfiguration_To_v1alpha1_KwokConfiguration(a.(*KwokConfiguration), b.(*v1alpha1.KwokConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KwokConfigurationOptions)(nil), (*v1alpha1.KwokConfigurationOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_KwokConfigurationOptions_To_v1alpha1_KwokConfigurationOptions(a.(*KwokConfigurationOptions), b.(*v1alpha1.KwokConfigurationOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.KwokConfigurationOptions)(nil), (*KwokConfigurationOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KwokConfigurationOptions_To_internalversion_KwokConfigurationOptions(a.(*v1alpha1.KwokConfigurationOptions), b.(*KwokConfigurationOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KwokctlConfiguration)(nil), (*v1alpha1.KwokctlConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_KwokctlConfiguration_To_v1alpha1_KwokctlConfiguration(a.(*KwokctlConfiguration), b.(*v1alpha1.KwokctlConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KwokctlConfigurationOptions)(nil), (*v1alpha1.KwokctlConfigurationOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_KwokctlConfigurationOptions_To_v1alpha1_KwokctlConfigurationOptions(a.(*KwokctlConfigurationOptions), b.(*v1alpha1.KwokctlConfigurationOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ObjectSelector)(nil), (*v1alpha1.ObjectSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_ObjectSelector_To_v1alpha1_ObjectSelector(a.(*ObjectSelector), b.(*v1alpha1.ObjectSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ObjectSelector)(nil), (*ObjectSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ObjectSelector_To_internalversion_ObjectSelector(a.(*v1alpha1.ObjectSelector), b.(*ObjectSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Port)(nil), (*v1alpha1.Port)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_Port_To_v1alpha1_Port(a.(*Port), b.(*v1alpha1.Port), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Port)(nil), (*Port)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Port_To_internalversion_Port(a.(*v1alpha1.Port), b.(*Port), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PortForward)(nil), (*v1alpha1.PortForward)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_PortForward_To_v1alpha1_PortForward(a.(*PortForward), b.(*v1alpha1.PortForward), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PortForwardSpec)(nil), (*v1alpha1.PortForwardSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_PortForwardSpec_To_v1alpha1_PortForwardSpec(a.(*PortForwardSpec), b.(*v1alpha1.PortForwardSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PortForwardSpec)(nil), (*PortForwardSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PortForwardSpec_To_internalversion_PortForwardSpec(a.(*v1alpha1.PortForwardSpec), b.(*PortForwardSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SelectorRequirement)(nil), (*v1alpha1.SelectorRequirement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_SelectorRequirement_To_v1alpha1_SelectorRequirement(a.(*SelectorRequirement), b.(*v1alpha1.SelectorRequirement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.SelectorRequirement)(nil), (*SelectorRequirement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SelectorRequirement_To_internalversion_SelectorRequirement(a.(*v1alpha1.SelectorRequirement), b.(*SelectorRequirement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Stage)(nil), (*v1alpha1.Stage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_Stage_To_v1alpha1_Stage(a.(*Stage), b.(*v1alpha1.Stage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StageDelay)(nil), (*v1alpha1.StageDelay)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_StageDelay_To_v1alpha1_StageDelay(a.(*StageDelay), b.(*v1alpha1.StageDelay), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.StageDelay)(nil), (*StageDelay)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StageDelay_To_internalversion_StageDelay(a.(*v1alpha1.StageDelay), b.(*StageDelay), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StageEvent)(nil), (*v1alpha1.StageEvent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_StageEvent_To_v1alpha1_StageEvent(a.(*StageEvent), b.(*v1alpha1.StageEvent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.StageEvent)(nil), (*StageEvent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StageEvent_To_internalversion_StageEvent(a.(*v1alpha1.StageEvent), b.(*StageEvent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StageFinalizers)(nil), (*v1alpha1.StageFinalizers)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_StageFinalizers_To_v1alpha1_StageFinalizers(a.(*StageFinalizers), b.(*v1alpha1.StageFinalizers), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.StageFinalizers)(nil), (*StageFinalizers)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StageFinalizers_To_internalversion_StageFinalizers(a.(*v1alpha1.StageFinalizers), b.(*StageFinalizers), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StageNext)(nil), (*v1alpha1.StageNext)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_StageNext_To_v1alpha1_StageNext(a.(*StageNext), b.(*v1alpha1.StageNext), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.StageNext)(nil), (*StageNext)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StageNext_To_internalversion_StageNext(a.(*v1alpha1.StageNext), b.(*StageNext), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StageResourceRef)(nil), (*v1alpha1.StageResourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_StageResourceRef_To_v1alpha1_StageResourceRef(a.(*StageResourceRef), b.(*v1alpha1.StageResourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.StageResourceRef)(nil), (*StageResourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StageResourceRef_To_internalversion_StageResourceRef(a.(*v1alpha1.StageResourceRef), b.(*StageResourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StageSelector)(nil), (*v1alpha1.StageSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_StageSelector_To_v1alpha1_StageSelector(a.(*StageSelector), b.(*v1alpha1.StageSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.StageSelector)(nil), (*StageSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StageSelector_To_internalversion_StageSelector(a.(*v1alpha1.StageSelector), b.(*StageSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StageSpec)(nil), (*v1alpha1.StageSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_StageSpec_To_v1alpha1_StageSpec(a.(*StageSpec), b.(*v1alpha1.StageSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.StageSpec)(nil), (*StageSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StageSpec_To_internalversion_StageSpec(a.(*v1alpha1.StageSpec), b.(*StageSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Volume)(nil), (*v1alpha1.Volume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_internalversion_Volume_To_v1alpha1_Volume(a.(*Volume), b.(*v1alpha1.Volume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Volume)(nil), (*Volume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Volume_To_internalversion_Volume(a.(*v1alpha1.Volume), b.(*Volume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha1.ClusterPortForward)(nil), (*ClusterPortForward)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterPortForward_To_internalversion_ClusterPortForward(a.(*v1alpha1.ClusterPortForward), b.(*ClusterPortForward), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha1.KwokConfiguration)(nil), (*KwokConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KwokConfiguration_To_internalversion_KwokConfiguration(a.(*v1alpha1.KwokConfiguration), b.(*KwokConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha1.KwokctlConfigurationOptions)(nil), (*KwokctlConfigurationOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KwokctlConfigurationOptions_To_internalversion_KwokctlConfigurationOptions(a.(*v1alpha1.KwokctlConfigurationOptions), b.(*KwokctlConfigurationOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha1.KwokctlConfiguration)(nil), (*KwokctlConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KwokctlConfiguration_To_internalversion_KwokctlConfiguration(a.(*v1alpha1.KwokctlConfiguration), b.(*KwokctlConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha1.PortForward)(nil), (*PortForward)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PortForward_To_internalversion_PortForward(a.(*v1alpha1.PortForward), b.(*PortForward), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha1.Stage)(nil), (*Stage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Stage_To_internalversion_Stage(a.(*v1alpha1.Stage), b.(*Stage), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_internalversion_ClusterPortForward_To_v1alpha1_ClusterPortForward(in *ClusterPortForward, out *v1alpha1.ClusterPortForward, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_internalversion_ClusterPortForwardSpec_To_v1alpha1_ClusterPortForwardSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_internalversion_ClusterPortForward_To_v1alpha1_ClusterPortForward is an autogenerated conversion function.
func Convert_internalversion_ClusterPortForward_To_v1alpha1_ClusterPortForward(in *ClusterPortForward, out *v1alpha1.ClusterPortForward, s conversion.Scope) error {
	return autoConvert_internalversion_ClusterPortForward_To_v1alpha1_ClusterPortForward(in, out, s)
}

func autoConvert_v1alpha1_ClusterPortForward_To_internalversion_ClusterPortForward(in *v1alpha1.ClusterPortForward, out *ClusterPortForward, s conversion.Scope) error {
	// WARNING: in.TypeMeta requires manual conversion: does not exist in peer-type
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterPortForwardSpec_To_internalversion_ClusterPortForwardSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_internalversion_ClusterPortForwardSpec_To_v1alpha1_ClusterPortForwardSpec(in *ClusterPortForwardSpec, out *v1alpha1.ClusterPortForwardSpec, s conversion.Scope) error {
	out.Selector = (*v1alpha1.ObjectSelector)(unsafe.Pointer(in.Selector))
	out.Forwards = *(*[]v1alpha1.Forward)(unsafe.Pointer(&in.Forwards))
	return nil
}

// Convert_internalversion_ClusterPortForwardSpec_To_v1alpha1_ClusterPortForwardSpec is an autogenerated conversion function.
func Convert_internalversion_ClusterPortForwardSpec_To_v1alpha1_ClusterPortForwardSpec(in *ClusterPortForwardSpec, out *v1alpha1.ClusterPortForwardSpec, s conversion.Scope) error {
	return autoConvert_internalversion_ClusterPortForwardSpec_To_v1alpha1_ClusterPortForwardSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterPortForwardSpec_To_internalversion_ClusterPortForwardSpec(in *v1alpha1.ClusterPortForwardSpec, out *ClusterPortForwardSpec, s conversion.Scope) error {
	out.Selector = (*ObjectSelector)(unsafe.Pointer(in.Selector))
	out.Forwards = *(*[]Forward)(unsafe.Pointer(&in.Forwards))
	return nil
}

// Convert_v1alpha1_ClusterPortForwardSpec_To_internalversion_ClusterPortForwardSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterPortForwardSpec_To_internalversion_ClusterPortForwardSpec(in *v1alpha1.ClusterPortForwardSpec, out *ClusterPortForwardSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterPortForwardSpec_To_internalversion_ClusterPortForwardSpec(in, out, s)
}

func autoConvert_internalversion_Component_To_v1alpha1_Component(in *Component, out *v1alpha1.Component, s conversion.Scope) error {
	out.Name = in.Name
	out.Links = *(*[]string)(unsafe.Pointer(&in.Links))
	out.Binary = in.Binary
	out.Image = in.Image
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.WorkDir = in.WorkDir
	out.Ports = *(*[]v1alpha1.Port)(unsafe.Pointer(&in.Ports))
	out.Envs = *(*[]v1alpha1.Env)(unsafe.Pointer(&in.Envs))
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1alpha1.Volume, len(*in))
		for i := range *in {
			if err := Convert_internalversion_Volume_To_v1alpha1_Volume(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Volumes = nil
	}
	out.Version = in.Version
	return nil
}

// Convert_internalversion_Component_To_v1alpha1_Component is an autogenerated conversion function.
func Convert_internalversion_Component_To_v1alpha1_Component(in *Component, out *v1alpha1.Component, s conversion.Scope) error {
	return autoConvert_internalversion_Component_To_v1alpha1_Component(in, out, s)
}

func autoConvert_v1alpha1_Component_To_internalversion_Component(in *v1alpha1.Component, out *Component, s conversion.Scope) error {
	out.Name = in.Name
	out.Links = *(*[]string)(unsafe.Pointer(&in.Links))
	out.Binary = in.Binary
	out.Image = in.Image
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.WorkDir = in.WorkDir
	out.Ports = *(*[]Port)(unsafe.Pointer(&in.Ports))
	out.Envs = *(*[]Env)(unsafe.Pointer(&in.Envs))
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]Volume, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Volume_To_internalversion_Volume(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Volumes = nil
	}
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_Component_To_internalversion_Component is an autogenerated conversion function.
func Convert_v1alpha1_Component_To_internalversion_Component(in *v1alpha1.Component, out *Component, s conversion.Scope) error {
	return autoConvert_v1alpha1_Component_To_internalversion_Component(in, out, s)
}

func autoConvert_internalversion_Env_To_v1alpha1_Env(in *Env, out *v1alpha1.Env, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_internalversion_Env_To_v1alpha1_Env is an autogenerated conversion function.
func Convert_internalversion_Env_To_v1alpha1_Env(in *Env, out *v1alpha1.Env, s conversion.Scope) error {
	return autoConvert_internalversion_Env_To_v1alpha1_Env(in, out, s)
}

func autoConvert_v1alpha1_Env_To_internalversion_Env(in *v1alpha1.Env, out *Env, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_Env_To_internalversion_Env is an autogenerated conversion function.
func Convert_v1alpha1_Env_To_internalversion_Env(in *v1alpha1.Env, out *Env, s conversion.Scope) error {
	return autoConvert_v1alpha1_Env_To_internalversion_Env(in, out, s)
}

func autoConvert_internalversion_ExpressionFromSource_To_v1alpha1_ExpressionFromSource(in *ExpressionFromSource, out *v1alpha1.ExpressionFromSource, s conversion.Scope) error {
	out.ExpressionFrom = in.ExpressionFrom
	return nil
}

// Convert_internalversion_ExpressionFromSource_To_v1alpha1_ExpressionFromSource is an autogenerated conversion function.
func Convert_internalversion_ExpressionFromSource_To_v1alpha1_ExpressionFromSource(in *ExpressionFromSource, out *v1alpha1.ExpressionFromSource, s conversion.Scope) error {
	return autoConvert_internalversion_ExpressionFromSource_To_v1alpha1_ExpressionFromSource(in, out, s)
}

func autoConvert_v1alpha1_ExpressionFromSource_To_internalversion_ExpressionFromSource(in *v1alpha1.ExpressionFromSource, out *ExpressionFromSource, s conversion.Scope) error {
	out.ExpressionFrom = in.ExpressionFrom
	return nil
}

// Convert_v1alpha1_ExpressionFromSource_To_internalversion_ExpressionFromSource is an autogenerated conversion function.
func Convert_v1alpha1_ExpressionFromSource_To_internalversion_ExpressionFromSource(in *v1alpha1.ExpressionFromSource, out *ExpressionFromSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExpressionFromSource_To_internalversion_ExpressionFromSource(in, out, s)
}

func autoConvert_internalversion_FinalizerItem_To_v1alpha1_FinalizerItem(in *FinalizerItem, out *v1alpha1.FinalizerItem, s conversion.Scope) error {
	out.Value = in.Value
	return nil
}

// Convert_internalversion_FinalizerItem_To_v1alpha1_FinalizerItem is an autogenerated conversion function.
func Convert_internalversion_FinalizerItem_To_v1alpha1_FinalizerItem(in *FinalizerItem, out *v1alpha1.FinalizerItem, s conversion.Scope) error {
	return autoConvert_internalversion_FinalizerItem_To_v1alpha1_FinalizerItem(in, out, s)
}

func autoConvert_v1alpha1_FinalizerItem_To_internalversion_FinalizerItem(in *v1alpha1.FinalizerItem, out *FinalizerItem, s conversion.Scope) error {
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_FinalizerItem_To_internalversion_FinalizerItem is an autogenerated conversion function.
func Convert_v1alpha1_FinalizerItem_To_internalversion_FinalizerItem(in *v1alpha1.FinalizerItem, out *FinalizerItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_FinalizerItem_To_internalversion_FinalizerItem(in, out, s)
}

func autoConvert_internalversion_Forward_To_v1alpha1_Forward(in *Forward, out *v1alpha1.Forward, s conversion.Scope) error {
	out.Ports = *(*[]int32)(unsafe.Pointer(&in.Ports))
	out.Target = (*v1alpha1.ForwardTarget)(unsafe.Pointer(in.Target))
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	return nil
}

// Convert_internalversion_Forward_To_v1alpha1_Forward is an autogenerated conversion function.
func Convert_internalversion_Forward_To_v1alpha1_Forward(in *Forward, out *v1alpha1.Forward, s conversion.Scope) error {
	return autoConvert_internalversion_Forward_To_v1alpha1_Forward(in, out, s)
}

func autoConvert_v1alpha1_Forward_To_internalversion_Forward(in *v1alpha1.Forward, out *Forward, s conversion.Scope) error {
	out.Ports = *(*[]int32)(unsafe.Pointer(&in.Ports))
	out.Target = (*ForwardTarget)(unsafe.Pointer(in.Target))
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	return nil
}

// Convert_v1alpha1_Forward_To_internalversion_Forward is an autogenerated conversion function.
func Convert_v1alpha1_Forward_To_internalversion_Forward(in *v1alpha1.Forward, out *Forward, s conversion.Scope) error {
	return autoConvert_v1alpha1_Forward_To_internalversion_Forward(in, out, s)
}

func autoConvert_internalversion_ForwardTarget_To_v1alpha1_ForwardTarget(in *ForwardTarget, out *v1alpha1.ForwardTarget, s conversion.Scope) error {
	out.Port = in.Port
	out.Address = in.Address
	return nil
}

// Convert_internalversion_ForwardTarget_To_v1alpha1_ForwardTarget is an autogenerated conversion function.
func Convert_internalversion_ForwardTarget_To_v1alpha1_ForwardTarget(in *ForwardTarget, out *v1alpha1.ForwardTarget, s conversion.Scope) error {
	return autoConvert_internalversion_ForwardTarget_To_v1alpha1_ForwardTarget(in, out, s)
}

func autoConvert_v1alpha1_ForwardTarget_To_internalversion_ForwardTarget(in *v1alpha1.ForwardTarget, out *ForwardTarget, s conversion.Scope) error {
	out.Port = in.Port
	out.Address = in.Address
	return nil
}

// Convert_v1alpha1_ForwardTarget_To_internalversion_ForwardTarget is an autogenerated conversion function.
func Convert_v1alpha1_ForwardTarget_To_internalversion_ForwardTarget(in *v1alpha1.ForwardTarget, out *ForwardTarget, s conversion.Scope) error {
	return autoConvert_v1alpha1_ForwardTarget_To_internalversion_ForwardTarget(in, out, s)
}

func autoConvert_internalversion_KwokConfiguration_To_v1alpha1_KwokConfiguration(in *KwokConfiguration, out *v1alpha1.KwokConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_internalversion_KwokConfigurationOptions_To_v1alpha1_KwokConfigurationOptions(&in.Options, &out.Options, s); err != nil {
		return err
	}
	return nil
}

// Convert_internalversion_KwokConfiguration_To_v1alpha1_KwokConfiguration is an autogenerated conversion function.
func Convert_internalversion_KwokConfiguration_To_v1alpha1_KwokConfiguration(in *KwokConfiguration, out *v1alpha1.KwokConfiguration, s conversion.Scope) error {
	return autoConvert_internalversion_KwokConfiguration_To_v1alpha1_KwokConfiguration(in, out, s)
}

func autoConvert_v1alpha1_KwokConfiguration_To_internalversion_KwokConfiguration(in *v1alpha1.KwokConfiguration, out *KwokConfiguration, s conversion.Scope) error {
	// WARNING: in.TypeMeta requires manual conversion: does not exist in peer-type
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_KwokConfigurationOptions_To_internalversion_KwokConfigurationOptions(&in.Options, &out.Options, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_internalversion_KwokConfigurationOptions_To_v1alpha1_KwokConfigurationOptions(in *KwokConfigurationOptions, out *v1alpha1.KwokConfigurationOptions, s conversion.Scope) error {
	out.CIDR = in.CIDR
	out.NodeIP = in.NodeIP
	out.NodeName = in.NodeName
	out.NodePort = in.NodePort
	out.TLSCertFile = in.TLSCertFile
	out.TLSPrivateKeyFile = in.TLSPrivateKeyFile
	if err := v1.Convert_bool_To_Pointer_bool(&in.ManageAllNodes, &out.ManageAllNodes, s); err != nil {
		return err
	}
	out.ManageNodesWithAnnotationSelector = in.ManageNodesWithAnnotationSelector
	out.ManageNodesWithLabelSelector = in.ManageNodesWithLabelSelector
	out.DisregardStatusWithAnnotationSelector = in.DisregardStatusWithAnnotationSelector
	out.DisregardStatusWithLabelSelector = in.DisregardStatusWithLabelSelector
	out.ServerAddress = in.ServerAddress
	if err := v1.Convert_bool_To_Pointer_bool(&in.EnableCNI, &out.EnableCNI, s); err != nil {
		return err
	}
	if err := v1.Convert_bool_To_Pointer_bool(&in.EnableDebuggingHandlers, &out.EnableDebuggingHandlers, s); err != nil {
		return err
	}
	if err := v1.Convert_bool_To_Pointer_bool(&in.EnableContentionProfiling, &out.EnableContentionProfiling, s); err != nil {
		return err
	}
	if err := v1.Convert_bool_To_Pointer_bool(&in.EnableProfilingHandler, &out.EnableProfilingHandler, s); err != nil {
		return err
	}
	return nil
}

// Convert_internalversion_KwokConfigurationOptions_To_v1alpha1_KwokConfigurationOptions is an autogenerated conversion function.
func Convert_internalversion_KwokConfigurationOptions_To_v1alpha1_KwokConfigurationOptions(in *KwokConfigurationOptions, out *v1alpha1.KwokConfigurationOptions, s conversion.Scope) error {
	return autoConvert_internalversion_KwokConfigurationOptions_To_v1alpha1_KwokConfigurationOptions(in, out, s)
}

func autoConvert_v1alpha1_KwokConfigurationOptions_To_internalversion_KwokConfigurationOptions(in *v1alpha1.KwokConfigurationOptions, out *KwokConfigurationOptions, s conversion.Scope) error {
	out.CIDR = in.CIDR
	out.NodeIP = in.NodeIP
	out.NodeName = in.NodeName
	out.NodePort = in.NodePort
	out.TLSCertFile = in.TLSCertFile
	out.TLSPrivateKeyFile = in.TLSPrivateKeyFile
	if err := v1.Convert_Pointer_bool_To_bool(&in.ManageAllNodes, &out.ManageAllNodes, s); err != nil {
		return err
	}
	out.ManageNodesWithAnnotationSelector = in.ManageNodesWithAnnotationSelector
	out.ManageNodesWithLabelSelector = in.ManageNodesWithLabelSelector
	out.DisregardStatusWithAnnotationSelector = in.DisregardStatusWithAnnotationSelector
	out.DisregardStatusWithLabelSelector = in.DisregardStatusWithLabelSelector
	out.ServerAddress = in.ServerAddress
	if err := v1.Convert_Pointer_bool_To_bool(&in.EnableCNI, &out.EnableCNI, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_bool_To_bool(&in.EnableDebuggingHandlers, &out.EnableDebuggingHandlers, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_bool_To_bool(&in.EnableContentionProfiling, &out.EnableContentionProfiling, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_bool_To_bool(&in.EnableProfilingHandler, &out.EnableProfilingHandler, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_KwokConfigurationOptions_To_internalversion_KwokConfigurationOptions is an autogenerated conversion function.
func Convert_v1alpha1_KwokConfigurationOptions_To_internalversion_KwokConfigurationOptions(in *v1alpha1.KwokConfigurationOptions, out *KwokConfigurationOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_KwokConfigurationOptions_To_internalversion_KwokConfigurationOptions(in, out, s)
}

func autoConvert_internalversion_KwokctlConfiguration_To_v1alpha1_KwokctlConfiguration(in *KwokctlConfiguration, out *v1alpha1.KwokctlConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_internalversion_KwokctlConfigurationOptions_To_v1alpha1_KwokctlConfigurationOptions(&in.Options, &out.Options, s); err != nil {
		return err
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]v1alpha1.Component, len(*in))
		for i := range *in {
			if err := Convert_internalversion_Component_To_v1alpha1_Component(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Components = nil
	}
	return nil
}

// Convert_internalversion_KwokctlConfiguration_To_v1alpha1_KwokctlConfiguration is an autogenerated conversion function.
func Convert_internalversion_KwokctlConfiguration_To_v1alpha1_KwokctlConfiguration(in *KwokctlConfiguration, out *v1alpha1.KwokctlConfiguration, s conversion.Scope) error {
	return autoConvert_internalversion_KwokctlConfiguration_To_v1alpha1_KwokctlConfiguration(in, out, s)
}

func autoConvert_v1alpha1_KwokctlConfiguration_To_internalversion_KwokctlConfiguration(in *v1alpha1.KwokctlConfiguration, out *KwokctlConfiguration, s conversion.Scope) error {
	// WARNING: in.TypeMeta requires manual conversion: does not exist in peer-type
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_KwokctlConfigurationOptions_To_internalversion_KwokctlConfigurationOptions(&in.Options, &out.Options, s); err != nil {
		return err
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]Component, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Component_To_internalversion_Component(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Components = nil
	}
	return nil
}

func autoConvert_internalversion_KwokctlConfigurationOptions_To_v1alpha1_KwokctlConfigurationOptions(in *KwokctlConfigurationOptions, out *v1alpha1.KwokctlConfigurationOptions, s conversion.Scope) error {
	out.KubeApiserverPort = in.KubeApiserverPort
	out.Runtime = in.Runtime
	out.Runtimes = *(*[]string)(unsafe.Pointer(&in.Runtimes))
	out.PrometheusPort = in.PrometheusPort
	out.KwokVersion = in.KwokVersion
	out.KubeVersion = in.KubeVersion
	out.EtcdVersion = in.EtcdVersion
	out.PrometheusVersion = in.PrometheusVersion
	out.DockerComposeVersion = in.DockerComposeVersion
	out.KindVersion = in.KindVersion
	if err := v1.Convert_bool_To_Pointer_bool(&in.SecurePort, &out.SecurePort, s); err != nil {
		return err
	}
	if err := v1.Convert_bool_To_Pointer_bool(&in.QuietPull, &out.QuietPull, s); err != nil {
		return err
	}
	out.KubeSchedulerConfig = in.KubeSchedulerConfig
	if err := v1.Convert_bool_To_Pointer_bool(&in.DisableKubeScheduler, &out.DisableKubeScheduler, s); err != nil {
		return err
	}
	if err := v1.Convert_bool_To_Pointer_bool(&in.DisableKubeControllerManager, &out.DisableKubeControllerManager, s); err != nil {
		return err
	}
	out.EtcdImage = in.EtcdImage
	out.KubeApiserverImage = in.KubeApiserverImage
	out.KubeControllerManagerImage = in.KubeControllerManagerImage
	out.KubeSchedulerImage = in.KubeSchedulerImage
	out.KwokControllerImage = in.KwokControllerImage
	out.PrometheusImage = in.PrometheusImage
	out.KindNodeImage = in.KindNodeImage
	out.BinSuffix = in.BinSuffix
	out.KubeApiserverBinary = in.KubeApiserverBinary
	out.KubeControllerManagerBinary = in.KubeControllerManagerBinary
	out.KubeSchedulerBinary = in.KubeSchedulerBinary
	out.KubectlBinary = in.KubectlBinary
	out.EtcdBinary = in.EtcdBinary
	out.EtcdBinaryTar = in.EtcdBinaryTar
	out.KwokControllerBinary = in.KwokControllerBinary
	out.PrometheusBinary = in.PrometheusBinary
	out.PrometheusBinaryTar = in.PrometheusBinaryTar
	out.DockerComposeBinary = in.DockerComposeBinary
	out.KindBinary = in.KindBinary
	out.Mode = in.Mode
	out.KubeFeatureGates = in.KubeFeatureGates
	out.KubeRuntimeConfig = in.KubeRuntimeConfig
	out.KubeAuditPolicy = in.KubeAuditPolicy
	if err := v1.Convert_bool_To_Pointer_bool(&in.KubeAuthorization, &out.KubeAuthorization, s); err != nil {
		return err
	}
	out.EtcdPeerPort = in.EtcdPeerPort
	out.EtcdPort = in.EtcdPort
	out.KubeControllerManagerPort = in.KubeControllerManagerPort
	out.KubeSchedulerPort = in.KubeSchedulerPort
	out.KwokControllerPort = in.KwokControllerPort
	out.CacheDir = in.CacheDir
	out.KubeControllerManagerNodeMonitorPeriodMilliseconds = in.KubeControllerManagerNodeMonitorPeriodMilliseconds
	out.KubeControllerManagerNodeMonitorGracePeriodMilliseconds = in.KubeControllerManagerNodeMonitorGracePeriodMilliseconds
	out.NodeStatusUpdateFrequencyMilliseconds = in.NodeStatusUpdateFrequencyMilliseconds
	return nil
}

// Convert_internalversion_KwokctlConfigurationOptions_To_v1alpha1_KwokctlConfigurationOptions is an autogenerated conversion function.
func Convert_internalversion_KwokctlConfigurationOptions_To_v1alpha1_KwokctlConfigurationOptions(in *KwokctlConfigurationOptions, out *v1alpha1.KwokctlConfigurationOptions, s conversion.Scope) error {
	return autoConvert_internalversion_KwokctlConfigurationOptions_To_v1alpha1_KwokctlConfigurationOptions(in, out, s)
}

func autoConvert_v1alpha1_KwokctlConfigurationOptions_To_internalversion_KwokctlConfigurationOptions(in *v1alpha1.KwokctlConfigurationOptions, out *KwokctlConfigurationOptions, s conversion.Scope) error {
	out.KubeApiserverPort = in.KubeApiserverPort
	out.Runtime = in.Runtime
	out.Runtimes = *(*[]string)(unsafe.Pointer(&in.Runtimes))
	out.PrometheusPort = in.PrometheusPort
	out.KwokVersion = in.KwokVersion
	out.KubeVersion = in.KubeVersion
	out.EtcdVersion = in.EtcdVersion
	out.PrometheusVersion = in.PrometheusVersion
	out.DockerComposeVersion = in.DockerComposeVersion
	out.KindVersion = in.KindVersion
	if err := v1.Convert_Pointer_bool_To_bool(&in.SecurePort, &out.SecurePort, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_bool_To_bool(&in.QuietPull, &out.QuietPull, s); err != nil {
		return err
	}
	out.KubeSchedulerConfig = in.KubeSchedulerConfig
	if err := v1.Convert_Pointer_bool_To_bool(&in.DisableKubeScheduler, &out.DisableKubeScheduler, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_bool_To_bool(&in.DisableKubeControllerManager, &out.DisableKubeControllerManager, s); err != nil {
		return err
	}
	// WARNING: in.KubeImagePrefix requires manual conversion: does not exist in peer-type
	// WARNING: in.EtcdImagePrefix requires manual conversion: does not exist in peer-type
	// WARNING: in.KwokImagePrefix requires manual conversion: does not exist in peer-type
	// WARNING: in.PrometheusImagePrefix requires manual conversion: does not exist in peer-type
	out.EtcdImage = in.EtcdImage
	out.KubeApiserverImage = in.KubeApiserverImage
	out.KubeControllerManagerImage = in.KubeControllerManagerImage
	out.KubeSchedulerImage = in.KubeSchedulerImage
	out.KwokControllerImage = in.KwokControllerImage
	out.PrometheusImage = in.PrometheusImage
	// WARNING: in.KindNodeImagePrefix requires manual conversion: does not exist in peer-type
	out.KindNodeImage = in.KindNodeImage
	out.BinSuffix = in.BinSuffix
	// WARNING: in.KubeBinaryPrefix requires manual conversion: does not exist in peer-type
	out.KubeApiserverBinary = in.KubeApiserverBinary
	out.KubeControllerManagerBinary = in.KubeControllerManagerBinary
	out.KubeSchedulerBinary = in.KubeSchedulerBinary
	out.KubectlBinary = in.KubectlBinary
	// WARNING: in.EtcdBinaryPrefix requires manual conversion: does not exist in peer-type
	out.EtcdBinary = in.EtcdBinary
	out.EtcdBinaryTar = in.EtcdBinaryTar
	// WARNING: in.KwokBinaryPrefix requires manual conversion: does not exist in peer-type
	out.KwokControllerBinary = in.KwokControllerBinary
	// WARNING: in.PrometheusBinaryPrefix requires manual conversion: does not exist in peer-type
	out.PrometheusBinary = in.PrometheusBinary
	out.PrometheusBinaryTar = in.PrometheusBinaryTar
	// WARNING: in.DockerComposeBinaryPrefix requires manual conversion: does not exist in peer-type
	out.DockerComposeBinary = in.DockerComposeBinary
	// WARNING: in.KindBinaryPrefix requires manual conversion: does not exist in peer-type
	out.KindBinary = in.KindBinary
	out.Mode = in.Mode
	out.KubeFeatureGates = in.KubeFeatureGates
	out.KubeRuntimeConfig = in.KubeRuntimeConfig
	out.KubeAuditPolicy = in.KubeAuditPolicy
	if err := v1.Convert_Pointer_bool_To_bool(&in.KubeAuthorization, &out.KubeAuthorization, s); err != nil {
		return err
	}
	out.EtcdPeerPort = in.EtcdPeerPort
	out.EtcdPort = in.EtcdPort
	out.KubeControllerManagerPort = in.KubeControllerManagerPort
	out.KubeSchedulerPort = in.KubeSchedulerPort
	out.KwokControllerPort = in.KwokControllerPort
	out.CacheDir = in.CacheDir
	out.KubeControllerManagerNodeMonitorPeriodMilliseconds = in.KubeControllerManagerNodeMonitorPeriodMilliseconds
	out.KubeControllerManagerNodeMonitorGracePeriodMilliseconds = in.KubeControllerManagerNodeMonitorGracePeriodMilliseconds
	out.NodeStatusUpdateFrequencyMilliseconds = in.NodeStatusUpdateFrequencyMilliseconds
	return nil
}

func autoConvert_internalversion_ObjectSelector_To_v1alpha1_ObjectSelector(in *ObjectSelector, out *v1alpha1.ObjectSelector, s conversion.Scope) error {
	out.MatchNamespaces = *(*[]string)(unsafe.Pointer(&in.MatchNamespaces))
	out.MatchNames = *(*[]string)(unsafe.Pointer(&in.MatchNames))
	return nil
}

// Convert_internalversion_ObjectSelector_To_v1alpha1_ObjectSelector is an autogenerated conversion function.
func Convert_internalversion_ObjectSelector_To_v1alpha1_ObjectSelector(in *ObjectSelector, out *v1alpha1.ObjectSelector, s conversion.Scope) error {
	return autoConvert_internalversion_ObjectSelector_To_v1alpha1_ObjectSelector(in, out, s)
}

func autoConvert_v1alpha1_ObjectSelector_To_internalversion_ObjectSelector(in *v1alpha1.ObjectSelector, out *ObjectSelector, s conversion.Scope) error {
	out.MatchNamespaces = *(*[]string)(unsafe.Pointer(&in.MatchNamespaces))
	out.MatchNames = *(*[]string)(unsafe.Pointer(&in.MatchNames))
	return nil
}

// Convert_v1alpha1_ObjectSelector_To_internalversion_ObjectSelector is an autogenerated conversion function.
func Convert_v1alpha1_ObjectSelector_To_internalversion_ObjectSelector(in *v1alpha1.ObjectSelector, out *ObjectSelector, s conversion.Scope) error {
	return autoConvert_v1alpha1_ObjectSelector_To_internalversion_ObjectSelector(in, out, s)
}

func autoConvert_internalversion_Port_To_v1alpha1_Port(in *Port, out *v1alpha1.Port, s conversion.Scope) error {
	out.Name = in.Name
	out.Port = in.Port
	out.HostPort = in.HostPort
	out.Protocol = v1alpha1.Protocol(in.Protocol)
	return nil
}

// Convert_internalversion_Port_To_v1alpha1_Port is an autogenerated conversion function.
func Convert_internalversion_Port_To_v1alpha1_Port(in *Port, out *v1alpha1.Port, s conversion.Scope) error {
	return autoConvert_internalversion_Port_To_v1alpha1_Port(in, out, s)
}

func autoConvert_v1alpha1_Port_To_internalversion_Port(in *v1alpha1.Port, out *Port, s conversion.Scope) error {
	out.Name = in.Name
	out.Port = in.Port
	out.HostPort = in.HostPort
	out.Protocol = Protocol(in.Protocol)
	return nil
}

// Convert_v1alpha1_Port_To_internalversion_Port is an autogenerated conversion function.
func Convert_v1alpha1_Port_To_internalversion_Port(in *v1alpha1.Port, out *Port, s conversion.Scope) error {
	return autoConvert_v1alpha1_Port_To_internalversion_Port(in, out, s)
}

func autoConvert_internalversion_PortForward_To_v1alpha1_PortForward(in *PortForward, out *v1alpha1.PortForward, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_internalversion_PortForwardSpec_To_v1alpha1_PortForwardSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_internalversion_PortForward_To_v1alpha1_PortForward is an autogenerated conversion function.
func Convert_internalversion_PortForward_To_v1alpha1_PortForward(in *PortForward, out *v1alpha1.PortForward, s conversion.Scope) error {
	return autoConvert_internalversion_PortForward_To_v1alpha1_PortForward(in, out, s)
}

func autoConvert_v1alpha1_PortForward_To_internalversion_PortForward(in *v1alpha1.PortForward, out *PortForward, s conversion.Scope) error {
	// WARNING: in.TypeMeta requires manual conversion: does not exist in peer-type
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PortForwardSpec_To_internalversion_PortForwardSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_internalversion_PortForwardSpec_To_v1alpha1_PortForwardSpec(in *PortForwardSpec, out *v1alpha1.PortForwardSpec, s conversion.Scope) error {
	out.Forwards = *(*[]v1alpha1.Forward)(unsafe.Pointer(&in.Forwards))
	return nil
}

// Convert_internalversion_PortForwardSpec_To_v1alpha1_PortForwardSpec is an autogenerated conversion function.
func Convert_internalversion_PortForwardSpec_To_v1alpha1_PortForwardSpec(in *PortForwardSpec, out *v1alpha1.PortForwardSpec, s conversion.Scope) error {
	return autoConvert_internalversion_PortForwardSpec_To_v1alpha1_PortForwardSpec(in, out, s)
}

func autoConvert_v1alpha1_PortForwardSpec_To_internalversion_PortForwardSpec(in *v1alpha1.PortForwardSpec, out *PortForwardSpec, s conversion.Scope) error {
	out.Forwards = *(*[]Forward)(unsafe.Pointer(&in.Forwards))
	return nil
}

// Convert_v1alpha1_PortForwardSpec_To_internalversion_PortForwardSpec is an autogenerated conversion function.
func Convert_v1alpha1_PortForwardSpec_To_internalversion_PortForwardSpec(in *v1alpha1.PortForwardSpec, out *PortForwardSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PortForwardSpec_To_internalversion_PortForwardSpec(in, out, s)
}

func autoConvert_internalversion_SelectorRequirement_To_v1alpha1_SelectorRequirement(in *SelectorRequirement, out *v1alpha1.SelectorRequirement, s conversion.Scope) error {
	out.Key = in.Key
	out.Operator = v1alpha1.SelectorOperator(in.Operator)
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_internalversion_SelectorRequirement_To_v1alpha1_SelectorRequirement is an autogenerated conversion function.
func Convert_internalversion_SelectorRequirement_To_v1alpha1_SelectorRequirement(in *SelectorRequirement, out *v1alpha1.SelectorRequirement, s conversion.Scope) error {
	return autoConvert_internalversion_SelectorRequirement_To_v1alpha1_SelectorRequirement(in, out, s)
}

func autoConvert_v1alpha1_SelectorRequirement_To_internalversion_SelectorRequirement(in *v1alpha1.SelectorRequirement, out *SelectorRequirement, s conversion.Scope) error {
	out.Key = in.Key
	out.Operator = SelectorOperator(in.Operator)
	out.Values = *(*[]string)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_v1alpha1_SelectorRequirement_To_internalversion_SelectorRequirement is an autogenerated conversion function.
func Convert_v1alpha1_SelectorRequirement_To_internalversion_SelectorRequirement(in *v1alpha1.SelectorRequirement, out *SelectorRequirement, s conversion.Scope) error {
	return autoConvert_v1alpha1_SelectorRequirement_To_internalversion_SelectorRequirement(in, out, s)
}

func autoConvert_internalversion_Stage_To_v1alpha1_Stage(in *Stage, out *v1alpha1.Stage, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_internalversion_StageSpec_To_v1alpha1_StageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_internalversion_Stage_To_v1alpha1_Stage is an autogenerated conversion function.
func Convert_internalversion_Stage_To_v1alpha1_Stage(in *Stage, out *v1alpha1.Stage, s conversion.Scope) error {
	return autoConvert_internalversion_Stage_To_v1alpha1_Stage(in, out, s)
}

func autoConvert_v1alpha1_Stage_To_internalversion_Stage(in *v1alpha1.Stage, out *Stage, s conversion.Scope) error {
	// WARNING: in.TypeMeta requires manual conversion: does not exist in peer-type
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_StageSpec_To_internalversion_StageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_internalversion_StageDelay_To_v1alpha1_StageDelay(in *StageDelay, out *v1alpha1.StageDelay, s conversion.Scope) error {
	out.DurationMilliseconds = (*int64)(unsafe.Pointer(in.DurationMilliseconds))
	out.DurationFrom = (*v1alpha1.ExpressionFromSource)(unsafe.Pointer(in.DurationFrom))
	out.JitterDurationMilliseconds = (*int64)(unsafe.Pointer(in.JitterDurationMilliseconds))
	out.JitterDurationFrom = (*v1alpha1.ExpressionFromSource)(unsafe.Pointer(in.JitterDurationFrom))
	return nil
}

// Convert_internalversion_StageDelay_To_v1alpha1_StageDelay is an autogenerated conversion function.
func Convert_internalversion_StageDelay_To_v1alpha1_StageDelay(in *StageDelay, out *v1alpha1.StageDelay, s conversion.Scope) error {
	return autoConvert_internalversion_StageDelay_To_v1alpha1_StageDelay(in, out, s)
}

func autoConvert_v1alpha1_StageDelay_To_internalversion_StageDelay(in *v1alpha1.StageDelay, out *StageDelay, s conversion.Scope) error {
	out.DurationMilliseconds = (*int64)(unsafe.Pointer(in.DurationMilliseconds))
	out.DurationFrom = (*ExpressionFromSource)(unsafe.Pointer(in.DurationFrom))
	out.JitterDurationMilliseconds = (*int64)(unsafe.Pointer(in.JitterDurationMilliseconds))
	out.JitterDurationFrom = (*ExpressionFromSource)(unsafe.Pointer(in.JitterDurationFrom))
	return nil
}

// Convert_v1alpha1_StageDelay_To_internalversion_StageDelay is an autogenerated conversion function.
func Convert_v1alpha1_StageDelay_To_internalversion_StageDelay(in *v1alpha1.StageDelay, out *StageDelay, s conversion.Scope) error {
	return autoConvert_v1alpha1_StageDelay_To_internalversion_StageDelay(in, out, s)
}

func autoConvert_internalversion_StageEvent_To_v1alpha1_StageEvent(in *StageEvent, out *v1alpha1.StageEvent, s conversion.Scope) error {
	out.Type = in.Type
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_internalversion_StageEvent_To_v1alpha1_StageEvent is an autogenerated conversion function.
func Convert_internalversion_StageEvent_To_v1alpha1_StageEvent(in *StageEvent, out *v1alpha1.StageEvent, s conversion.Scope) error {
	return autoConvert_internalversion_StageEvent_To_v1alpha1_StageEvent(in, out, s)
}

func autoConvert_v1alpha1_StageEvent_To_internalversion_StageEvent(in *v1alpha1.StageEvent, out *StageEvent, s conversion.Scope) error {
	out.Type = in.Type
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_StageEvent_To_internalversion_StageEvent is an autogenerated conversion function.
func Convert_v1alpha1_StageEvent_To_internalversion_StageEvent(in *v1alpha1.StageEvent, out *StageEvent, s conversion.Scope) error {
	return autoConvert_v1alpha1_StageEvent_To_internalversion_StageEvent(in, out, s)
}

func autoConvert_internalversion_StageFinalizers_To_v1alpha1_StageFinalizers(in *StageFinalizers, out *v1alpha1.StageFinalizers, s conversion.Scope) error {
	out.Add = *(*[]v1alpha1.FinalizerItem)(unsafe.Pointer(&in.Add))
	out.Remove = *(*[]v1alpha1.FinalizerItem)(unsafe.Pointer(&in.Remove))
	out.Empty = in.Empty
	return nil
}

// Convert_internalversion_StageFinalizers_To_v1alpha1_StageFinalizers is an autogenerated conversion function.
func Convert_internalversion_StageFinalizers_To_v1alpha1_StageFinalizers(in *StageFinalizers, out *v1alpha1.StageFinalizers, s conversion.Scope) error {
	return autoConvert_internalversion_StageFinalizers_To_v1alpha1_StageFinalizers(in, out, s)
}

func autoConvert_v1alpha1_StageFinalizers_To_internalversion_StageFinalizers(in *v1alpha1.StageFinalizers, out *StageFinalizers, s conversion.Scope) error {
	out.Add = *(*[]FinalizerItem)(unsafe.Pointer(&in.Add))
	out.Remove = *(*[]FinalizerItem)(unsafe.Pointer(&in.Remove))
	out.Empty = in.Empty
	return nil
}

// Convert_v1alpha1_StageFinalizers_To_internalversion_StageFinalizers is an autogenerated conversion function.
func Convert_v1alpha1_StageFinalizers_To_internalversion_StageFinalizers(in *v1alpha1.StageFinalizers, out *StageFinalizers, s conversion.Scope) error {
	return autoConvert_v1alpha1_StageFinalizers_To_internalversion_StageFinalizers(in, out, s)
}

func autoConvert_internalversion_StageNext_To_v1alpha1_StageNext(in *StageNext, out *v1alpha1.StageNext, s conversion.Scope) error {
	out.Event = (*v1alpha1.StageEvent)(unsafe.Pointer(in.Event))
	out.Finalizers = (*v1alpha1.StageFinalizers)(unsafe.Pointer(in.Finalizers))
	out.Delete = in.Delete
	out.StatusTemplate = in.StatusTemplate
	return nil
}

// Convert_internalversion_StageNext_To_v1alpha1_StageNext is an autogenerated conversion function.
func Convert_internalversion_StageNext_To_v1alpha1_StageNext(in *StageNext, out *v1alpha1.StageNext, s conversion.Scope) error {
	return autoConvert_internalversion_StageNext_To_v1alpha1_StageNext(in, out, s)
}

func autoConvert_v1alpha1_StageNext_To_internalversion_StageNext(in *v1alpha1.StageNext, out *StageNext, s conversion.Scope) error {
	out.Event = (*StageEvent)(unsafe.Pointer(in.Event))
	out.Finalizers = (*StageFinalizers)(unsafe.Pointer(in.Finalizers))
	out.Delete = in.Delete
	out.StatusTemplate = in.StatusTemplate
	return nil
}

// Convert_v1alpha1_StageNext_To_internalversion_StageNext is an autogenerated conversion function.
func Convert_v1alpha1_StageNext_To_internalversion_StageNext(in *v1alpha1.StageNext, out *StageNext, s conversion.Scope) error {
	return autoConvert_v1alpha1_StageNext_To_internalversion_StageNext(in, out, s)
}

func autoConvert_internalversion_StageResourceRef_To_v1alpha1_StageResourceRef(in *StageResourceRef, out *v1alpha1.StageResourceRef, s conversion.Scope) error {
	out.APIGroup = in.APIGroup
	out.Kind = in.Kind
	return nil
}

// Convert_internalversion_StageResourceRef_To_v1alpha1_StageResourceRef is an autogenerated conversion function.
func Convert_internalversion_StageResourceRef_To_v1alpha1_StageResourceRef(in *StageResourceRef, out *v1alpha1.StageResourceRef, s conversion.Scope) error {
	return autoConvert_internalversion_StageResourceRef_To_v1alpha1_StageResourceRef(in, out, s)
}

func autoConvert_v1alpha1_StageResourceRef_To_internalversion_StageResourceRef(in *v1alpha1.StageResourceRef, out *StageResourceRef, s conversion.Scope) error {
	out.APIGroup = in.APIGroup
	out.Kind = in.Kind
	return nil
}

// Convert_v1alpha1_StageResourceRef_To_internalversion_StageResourceRef is an autogenerated conversion function.
func Convert_v1alpha1_StageResourceRef_To_internalversion_StageResourceRef(in *v1alpha1.StageResourceRef, out *StageResourceRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_StageResourceRef_To_internalversion_StageResourceRef(in, out, s)
}

func autoConvert_internalversion_StageSelector_To_v1alpha1_StageSelector(in *StageSelector, out *v1alpha1.StageSelector, s conversion.Scope) error {
	out.MatchLabels = *(*map[string]string)(unsafe.Pointer(&in.MatchLabels))
	out.MatchAnnotations = *(*map[string]string)(unsafe.Pointer(&in.MatchAnnotations))
	out.MatchExpressions = *(*[]v1alpha1.SelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	return nil
}

// Convert_internalversion_StageSelector_To_v1alpha1_StageSelector is an autogenerated conversion function.
func Convert_internalversion_StageSelector_To_v1alpha1_StageSelector(in *StageSelector, out *v1alpha1.StageSelector, s conversion.Scope) error {
	return autoConvert_internalversion_StageSelector_To_v1alpha1_StageSelector(in, out, s)
}

func autoConvert_v1alpha1_StageSelector_To_internalversion_StageSelector(in *v1alpha1.StageSelector, out *StageSelector, s conversion.Scope) error {
	out.MatchLabels = *(*map[string]string)(unsafe.Pointer(&in.MatchLabels))
	out.MatchAnnotations = *(*map[string]string)(unsafe.Pointer(&in.MatchAnnotations))
	out.MatchExpressions = *(*[]SelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	return nil
}

// Convert_v1alpha1_StageSelector_To_internalversion_StageSelector is an autogenerated conversion function.
func Convert_v1alpha1_StageSelector_To_internalversion_StageSelector(in *v1alpha1.StageSelector, out *StageSelector, s conversion.Scope) error {
	return autoConvert_v1alpha1_StageSelector_To_internalversion_StageSelector(in, out, s)
}

func autoConvert_internalversion_StageSpec_To_v1alpha1_StageSpec(in *StageSpec, out *v1alpha1.StageSpec, s conversion.Scope) error {
	if err := Convert_internalversion_StageResourceRef_To_v1alpha1_StageResourceRef(&in.ResourceRef, &out.ResourceRef, s); err != nil {
		return err
	}
	out.Selector = (*v1alpha1.StageSelector)(unsafe.Pointer(in.Selector))
	out.Weight = in.Weight
	out.Delay = (*v1alpha1.StageDelay)(unsafe.Pointer(in.Delay))
	if err := Convert_internalversion_StageNext_To_v1alpha1_StageNext(&in.Next, &out.Next, s); err != nil {
		return err
	}
	return nil
}

// Convert_internalversion_StageSpec_To_v1alpha1_StageSpec is an autogenerated conversion function.
func Convert_internalversion_StageSpec_To_v1alpha1_StageSpec(in *StageSpec, out *v1alpha1.StageSpec, s conversion.Scope) error {
	return autoConvert_internalversion_StageSpec_To_v1alpha1_StageSpec(in, out, s)
}

func autoConvert_v1alpha1_StageSpec_To_internalversion_StageSpec(in *v1alpha1.StageSpec, out *StageSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_StageResourceRef_To_internalversion_StageResourceRef(&in.ResourceRef, &out.ResourceRef, s); err != nil {
		return err
	}
	out.Selector = (*StageSelector)(unsafe.Pointer(in.Selector))
	out.Weight = in.Weight
	out.Delay = (*StageDelay)(unsafe.Pointer(in.Delay))
	if err := Convert_v1alpha1_StageNext_To_internalversion_StageNext(&in.Next, &out.Next, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_StageSpec_To_internalversion_StageSpec is an autogenerated conversion function.
func Convert_v1alpha1_StageSpec_To_internalversion_StageSpec(in *v1alpha1.StageSpec, out *StageSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_StageSpec_To_internalversion_StageSpec(in, out, s)
}

func autoConvert_internalversion_Volume_To_v1alpha1_Volume(in *Volume, out *v1alpha1.Volume, s conversion.Scope) error {
	out.Name = in.Name
	if err := v1.Convert_bool_To_Pointer_bool(&in.ReadOnly, &out.ReadOnly, s); err != nil {
		return err
	}
	out.HostPath = in.HostPath
	out.MountPath = in.MountPath
	return nil
}

// Convert_internalversion_Volume_To_v1alpha1_Volume is an autogenerated conversion function.
func Convert_internalversion_Volume_To_v1alpha1_Volume(in *Volume, out *v1alpha1.Volume, s conversion.Scope) error {
	return autoConvert_internalversion_Volume_To_v1alpha1_Volume(in, out, s)
}

func autoConvert_v1alpha1_Volume_To_internalversion_Volume(in *v1alpha1.Volume, out *Volume, s conversion.Scope) error {
	out.Name = in.Name
	if err := v1.Convert_Pointer_bool_To_bool(&in.ReadOnly, &out.ReadOnly, s); err != nil {
		return err
	}
	out.HostPath = in.HostPath
	out.MountPath = in.MountPath
	return nil
}

// Convert_v1alpha1_Volume_To_internalversion_Volume is an autogenerated conversion function.
func Convert_v1alpha1_Volume_To_internalversion_Volume(in *v1alpha1.Volume, out *Volume, s conversion.Scope) error {
	return autoConvert_v1alpha1_Volume_To_internalversion_Volume(in, out, s)
}
