/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/kwok/pkg/apis/v1alpha1"
)

// FakeExternalMetrics implements ExternalMetricInterface
type FakeExternalMetrics struct {
	Fake *FakeKwokV1alpha1
	ns   string
}

var externalmetricsResource = v1alpha1.SchemeGroupVersion.WithResource("externalmetrics")

var externalmetricsKind = v1alpha1.SchemeGroupVersion.WithKind("ExternalMetric")

// Get takes name of the externalMetric, and returns the corresponding externalMetric object, and an error if there is any.
func (c *FakeExternalMetrics) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ExternalMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(externalmetricsResource, c.ns, name), &v1alpha1.ExternalMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalMetric), err
}

// List takes label and field selectors, and returns the list of ExternalMetrics that match those selectors.
func (c *FakeExternalMetrics) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ExternalMetricList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(externalmetricsResource, externalmetricsKind, c.ns, opts), &v1alpha1.ExternalMetricList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExternalMetricList{ListMeta: obj.(*v1alpha1.ExternalMetricList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExternalMetricList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested externalMetrics.
func (c *FakeExternalMetrics) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(externalmetricsResource, c.ns, opts))

}

// Create takes the representation of a externalMetric and creates it.  Returns the server's representation of the externalMetric, and an error, if there is any.
func (c *FakeExternalMetrics) Create(ctx context.Context, externalMetric *v1alpha1.ExternalMetric, opts v1.CreateOptions) (result *v1alpha1.ExternalMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(externalmetricsResource, c.ns, externalMetric), &v1alpha1.ExternalMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalMetric), err
}

// Update takes the representation of a externalMetric and updates it. Returns the server's representation of the externalMetric, and an error, if there is any.
func (c *FakeExternalMetrics) Update(ctx context.Context, externalMetric *v1alpha1.ExternalMetric, opts v1.UpdateOptions) (result *v1alpha1.ExternalMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(externalmetricsResource, c.ns, externalMetric), &v1alpha1.ExternalMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalMetric), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExternalMetrics) UpdateStatus(ctx context.Context, externalMetric *v1alpha1.ExternalMetric, opts v1.UpdateOptions) (*v1alpha1.ExternalMetric, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(externalmetricsResource, "status", c.ns, externalMetric), &v1alpha1.ExternalMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalMetric), err
}

// Delete takes name of the externalMetric and deletes it. Returns an error if one occurs.
func (c *FakeExternalMetrics) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(externalmetricsResource, c.ns, name, opts), &v1alpha1.ExternalMetric{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExternalMetrics) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(externalmetricsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExternalMetricList{})
	return err
}

// Patch applies the patch and returns the patched externalMetric.
func (c *FakeExternalMetrics) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ExternalMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(externalmetricsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ExternalMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExternalMetric), err
}
