/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/kwok/pkg/apis/v1alpha1"
)

// FakeClusterResourceUsages implements ClusterResourceUsageInterface
type FakeClusterResourceUsages struct {
	Fake *FakeKwokV1alpha1
}

var clusterresourceusagesResource = v1alpha1.SchemeGroupVersion.WithResource("clusterresourceusages")

var clusterresourceusagesKind = v1alpha1.SchemeGroupVersion.WithKind("ClusterResourceUsage")

// Get takes name of the clusterResourceUsage, and returns the corresponding clusterResourceUsage object, and an error if there is any.
func (c *FakeClusterResourceUsages) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterResourceUsage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterresourceusagesResource, name), &v1alpha1.ClusterResourceUsage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterResourceUsage), err
}

// List takes label and field selectors, and returns the list of ClusterResourceUsages that match those selectors.
func (c *FakeClusterResourceUsages) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterResourceUsageList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterresourceusagesResource, clusterresourceusagesKind, opts), &v1alpha1.ClusterResourceUsageList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterResourceUsageList{ListMeta: obj.(*v1alpha1.ClusterResourceUsageList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterResourceUsageList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterResourceUsages.
func (c *FakeClusterResourceUsages) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterresourceusagesResource, opts))
}

// Create takes the representation of a clusterResourceUsage and creates it.  Returns the server's representation of the clusterResourceUsage, and an error, if there is any.
func (c *FakeClusterResourceUsages) Create(ctx context.Context, clusterResourceUsage *v1alpha1.ClusterResourceUsage, opts v1.CreateOptions) (result *v1alpha1.ClusterResourceUsage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterresourceusagesResource, clusterResourceUsage), &v1alpha1.ClusterResourceUsage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterResourceUsage), err
}

// Update takes the representation of a clusterResourceUsage and updates it. Returns the server's representation of the clusterResourceUsage, and an error, if there is any.
func (c *FakeClusterResourceUsages) Update(ctx context.Context, clusterResourceUsage *v1alpha1.ClusterResourceUsage, opts v1.UpdateOptions) (result *v1alpha1.ClusterResourceUsage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterresourceusagesResource, clusterResourceUsage), &v1alpha1.ClusterResourceUsage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterResourceUsage), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterResourceUsages) UpdateStatus(ctx context.Context, clusterResourceUsage *v1alpha1.ClusterResourceUsage, opts v1.UpdateOptions) (*v1alpha1.ClusterResourceUsage, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterresourceusagesResource, "status", clusterResourceUsage), &v1alpha1.ClusterResourceUsage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterResourceUsage), err
}

// Delete takes name of the clusterResourceUsage and deletes it. Returns an error if one occurs.
func (c *FakeClusterResourceUsages) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterresourceusagesResource, name, opts), &v1alpha1.ClusterResourceUsage{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterResourceUsages) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterresourceusagesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterResourceUsageList{})
	return err
}

// Patch applies the patch and returns the patched clusterResourceUsage.
func (c *FakeClusterResourceUsages) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterResourceUsage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterresourceusagesResource, name, pt, data, subresources...), &v1alpha1.ClusterResourceUsage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterResourceUsage), err
}
