name: Releases
on:
  push:
    tags:
    - v*

env:
  PUSH: 'true'
  PRE_RELEASE: GA
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  packages: write

jobs:
  releases:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod
    - name: Set up QEMU
      uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build binary for registry.k8s.io
      if: ${{ github.repository == 'kubernetes-sigs/kwok' }}
      env:
        GH_RELEASE: ${{ github.repository }}
        IMAGE_PREFIX: registry.k8s.io/kwok
        BINARY_PREFIX: https://github.com/${{ github.repository }}/releases/download
      run: |
        REF=${{ github.ref }}
        GIT_TAG="${REF##*/}" make manifests cross-build
    - name: Build binary for ghcr.io
      if: ${{ github.repository != 'kubernetes-sigs/kwok' }}
      env:
        GH_RELEASE: ${{ github.repository }}
        IMAGE_PREFIX: ghcr.io/${{ github.repository }}
        BINARY_PREFIX: https://github.com/${{ github.repository }}/releases/download
      run: |
        REF=${{ github.ref }}
        GIT_TAG="${REF##*/}" make manifests cross-build
    - name: Build kwok image
      env:
        IMAGE_PREFIX: ghcr.io/${{ github.repository }}
      run: |
        REF=${{ github.ref }}
        GIT_TAG="${REF##*/}" make cross-image
    - name: Build cluster image
      env:
        IMAGE_PREFIX: ghcr.io/${{ github.repository }}
      run: |
        REF=${{ github.ref }}
        GIT_TAG="${REF##*/}" make cross-cluster-image
